export const SET_PROJECTS = 'SET_PROJECTS';
export const FETCH_PROJECTS_FAILED = ' FETCH_PROJECTS_FAILED';
export const SET_PROJECT = 'SET_PROJECT';
export const FETCH_PROJECT_FAILED = ' FETCH_PROJECT_FAILED';
export const SET_FEATURED_PROJECTS = 'SET_FEATURED_PROJECTS';
export const FETCH_FEATURED_PROJECTS_FAILED = 'SET_FEATURED_PROJECTS_FAILED';

export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';
export const SIGN_UP_LOADING = 'SIGN_UP_LOADING';
export const SIGN_UP_RESET = 'SIGN_UP_RESET';

export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';
export const SIGN_IN_LOADING = 'SIGN_IN_LOADING';
export const SIGN_IN_RESET = 'SIGN_IN_RESET';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';

export const JOIN_ROOM = 'JOIN_ROOM';
export const LEAVE_ROOM = 'LEAVE_ROOM';
export const ROOM_ACTION_FAILED = 'ROOM_ACTION_FAILED';

export const SET_ROOMS = 'SET_ROOMS';
export const SET_ROOMS_FAILED = 'SET_ROOMS_FAILED';